# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_auto_20170611_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ig_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
